set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle
call vundle#rc()

" Vundle itself
Bundle 'gmarik/vundle'

" Other plugins
Bundle 'scrooloose/syntastic'
    let g:syntastic_mode_map = { 'mode': 'active' }

Bundle 'scrooloose/nerdtree'

Bundle 'Valloric/YouCompleteMe'
    let g:ycm_extra_conf_globlist = ['~/.ycm_extra_conf.py']
    let g:ycm_key_list_select_completion = ['<C-n>']
    let g:ycm_key_list_previous_completion = ['<C-p>']

Bundle 'michalbachowski/vim-wombat256mod'

Bundle 'bling/vim-airline'

" Other options
filetype plugin indent on
let mapleader=","

colorscheme wombat256mod
syntax on
set number

" Backup, Swap, Undo
set noswapfile
set nobackup
set undofile
set undodir=~/.cache/
set viminfo+=n~/.cache/viminfo
set autoread

" Search
set ignorecase
set smartcase
set incsearch

" Indent
set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" History
set history=1024
set wildmode=longest:list,full

" Misc
set mouse=a
set completeopt=menu,menuone,longest
set tabpagemax=99999
set notimeout

" Maps
map <leader>n :NERDTreeToggle<ENTER>

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

inoremap jj <Esc>
nnoremap JJJJ <Nop>


